### PR TITLE
GET-APPOINTMENT-BY-APPOINTMENT-DATE

### PR DESCRIPTION
**Pull request by AnujaMane**
GET-APPOINTMENT-BY-APPOINTMENT-DATE

### CODE REVIEW

**Review by ram-chadar — APPROVED** [review]
looks good merge into main

**Comment by AnujaMane** [comment]
GET-APPOINTMENT-BY-APPOINTMENT-DATE

**Review by ram-chadar — APPROVED** [review]
looks good

**Comment by ram-chadar** [comment]
HMS-APPOINTMENT-GET-APPOINTMENT-BY-APPOINTMENT-DATE

**Pull request merged**
